data<-read.table("household_power_consumption.txt", sep=";", header = TRUE)
febdata_log<- subset(data, Date == "1/2/2007" | Date== "2/2/2007")
febdata_log_num<-as.numeric(paste(febdata_log$Global_active_power))
datetime<-paste(febdata_log$Date,febdata_log$Time)
datetime<-strptime(datetime, format= "%d/%m/%Y %H:%M:%S")
datetime<-as.POSIXct(datetime2)
png(file="plot2.png", height=480, width=480)
plot(febdata_log_num~datetime, type="l", ,xlab=NA, ylab="Global Active Power (kilowatts)")
dev.off()