data<-read.table("household_power_consumption.txt", sep=";", header = TRUE)
febdata_log<- subset(data, Date == "1/2/2007" | Date== "2/2/2007")
datetime<-paste(febdata_log$Date,febdata_log$Time)
datetime<-strptime(datetime, format= "%d/%m/%Y %H:%M:%S")
datetime<-as.POSIXct(datetime2)
Submetering_1<-as.numeric(paste(febdata_log$Sub_metering_1))
Submetering_2<-as.numeric(paste(febdata_log$Sub_metering_2))
Submetering_3<-as.numeric(paste(febdata_log$Sub_metering_3))
png(file="plot3.png", height=480, width=480)
plot(x=datetime, y=Submetering_1, type= "l", xlab="", ylab="Energy sub metering")
lines(datetime, Submetering_2, type="l", col="red")
lines(datetime, Submetering_3, type="l", col="blue")
legend("topright", col=c("black", "red", "blue"), lty=c(1,1,1), legend= c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()
